services:
  web:
    build: .
    container_name: kasirnusa-pathfinder
    restart: always
    ports:
      - "8081:8081"
    environment:
      - PORT=8081

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: kasirnusa-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - web
    profiles:
      - tunnel
